=== jquivio1606/1DAW/Lenguaje/EjerciciosClase/Boletín3/Ejercicio19.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="factura">
        <xs:complexType>
           <xs:all>
            <xs:element name ="datos-emisor">
                <xs:complexType>
                    <xs:sequence>
                        <xs:group ref="datosPersonales"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name ="datos-cliente">
                <xs:complexType>
                    <xs:sequence>
                        <xs:group ref="datosPersonales"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name ="detalle-factura">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name= "linea" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="descripcion" type = "xs:string"/>
                                    <xs:element name= "cantidad" type ="xs:integer"/>
                                    <xs:element name= "oferta" minOccurs="0"/>
                                    <xs:element name= "pvp" type ="xs:double"/>
                                </xs:sequence>
                                <xs:attribute name= "codigo-articulo" type = "xs:string"/>
                                <xs:attribute name= "tipo" type = "xs:string"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name= "importe" type = "xs:double"/>
                </xs:complexType>
            </xs:element>
           </xs:all>
           <xs:attribute name= "numero" use="required">
                <xs:simpleType>
                    <xs:restriction base= "xs:integer">
                        <xs:pattern value= "[0-9]+"/>
                    </xs:restriction>
                </xs:simpleType>
           </xs:attribute>
           <xs:attribute name= "fecha" type= "xs:date" use="required"/>
           <xs:attribute name= "moneda" type="xs:string" fixed="Euro"/>
        </xs:complexType>
    </xs:element>

    <xs:group name= "datosPersonales">
            <xs:sequence>
                <xs:element name= "nombre" type= "xs:string"/>
                <xs:element name = "cif" type= "xs:string"/>
                <xs:element name= "telefono" type ="xs:integer"/>
            </xs:sequence>
    </xs:group>
</xs:schema>

=== jquivio1606/1DAW/Lenguaje/EjerciciosClase/Boletín3/Ejercicio19.xml
<?xml version="1.0" encoding="UTF-8"?>

<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ejercicio19.xsd"
numero="27" fecha="2013-12-18" moneda="Euro">
    <datos-emisor>
        <nombre>Librería Pérez</nombre>
        <cif>44555666-B</cif>
        <telefono>777888999</telefono>
    </datos-emisor>
    <datos-cliente>
        <nombre>Biblioteca Txantrea</nombre>
        <cif>33111222-A</cif>
        <telefono>333999444</telefono>
    </datos-cliente>
    <detalle-factura importe="86.12">
        <linea codigo-articulo="AW7" tipo="Libro">
            <descripcion>Analítica Web 2.0</descripcion>
            <cantidad>1</cantidad>
            <oferta />
            <pvp>25.12</pvp>
        </linea>
        <linea codigo-articulo="CP5" tipo="DVD">
            <descripcion>Curso de HTML</descripcion>
            <cantidad>2</cantidad>
            <pvp>30.5</pvp>
        </linea>
    </detalle-factura>
</factura>
